CREATE TABLE TMP_VIDEOGAME 
(METASCORE VARCHAR2(200), 
 NOMBRE_JUEGO VARCHAR2(200), 
 NOMBRE_CONSOLA VARCHAR2(200), 
 NOTA_USUARIO VARCHAR2(200), 
 FECHA_NOTA VARCHAR2(20)
);

CREATE TABLE COMPANIA 
(ID_COMPANIA NUMBER NOT NULL ENABLE, 
 NOMBRE_COMPANIA VARCHAR2(150), 
 CONSTRAINT COMPAÑIA_PK PRIMARY KEY (ID_COMPANIA)
);

CREATE TABLE CONSOLA 
(ID_CONSOLA NUMBER NOT NULL ENABLE, 
 ID_COMPANIA NUMBER NOT NULL ENABLE, 
 NOMBRE_CONSOLA VARCHAR2(150), 
 CONSTRAINT CONSOLA_PK PRIMARY KEY (ID_CONSOLA), 
 CONSTRAINT CONSOLA_COMPANIA_FK FOREIGN KEY (ID_COMPANIA) REFERENCES COMPANIA (ID_COMPANIA) ENABLE
);

CREATE INDEX CONSOLA_ID_COMPANIA_IDX ON CONSOLA (ID_COMPANIA) 
;

CREATE TABLE JUEGO 
(ID_JUEGO NUMBER NOT NULL ENABLE, 
 ID_CONSOLA NUMBER NOT NULL ENABLE, 
 NOMBRE_JUEGO VARCHAR2(150), 
 CONSTRAINT JUEGOS_PK PRIMARY KEY (ID_JUEGO), 
 CONSTRAINT JUEGOS_CONSOLA_FK FOREIGN KEY (ID_CONSOLA) REFERENCES CONSOLA (ID_CONSOLA) ENABLE
);

CREATE INDEX JUEGO_ID_CONSOLA_IDX ON JUEGO (ID_CONSOLA) 
;

CREATE TABLE RANKING_JUEGO 
(ID_RANKING NUMBER NOT NULL ENABLE, 
 ID_JUEGO NUMBER NOT NULL ENABLE, 
 NOTA_USUARIO NUMBER(12,3), 
 FECHA_NOTA DATE, 
 METASCORE NUMBER, 
 CONSTRAINT RANKING_JUEGO_PK PRIMARY KEY (ID_RANKING), 
 CONSTRAINT RANKING_JUEGO_JUEGOS_FK FOREIGN KEY (ID_JUEGO) REFERENCES JUEGO (ID_JUEGO) ENABLE
);

CREATE INDEX RANKING_JUEGO_ID_JUEGO_IDX ON RANKING_JUEGO (ID_JUEGO) 
;